name: local_db_chat_app
description: local db chat app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  collection: ^1.19.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  skeletonizer: ^2.1.2
  timeago: ^3.7.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  drift_dev: ^2.30.1
  flutter_test:
    sdk: flutter
  flutter_test_goldens: ^0.0.7
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
